"""about author field added

Revision ID: 371f73ab80cf
Revises: 
Create Date: 2023-01-03 14:54:55.318891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371f73ab80cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_author', sa.Text(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personel', schema=None) as batch_op:
        batch_op.drop_column('about_author')

    # ### end Alembic commands ###
